services:
  gateway:
    image: nginx:latest
    depends_on:
      - users
      - auth
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - frontend_net
