version: "3.8"
services:
  users:
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    environment:
      - DEBUG=false

  orders:
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    environment:
      - DEBUG=false

  auth:
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    environment:
      - DEBUG=false

  gateway:
    ports:
      - "8080:80"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  db:
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure